const cvs=document.getElementById('game'),ctx=cvs.getContext('2d');
let W=1280,H=720,keys={},dir={left:false,right:false,up:false,down:false},lastTap={left:0,right:0};
function resize(){let r=innerWidth/innerHeight,cr=W/H;if(r>cr){cvs.style.height='100vh';cvs.style.width='auto'}else{cvs.style.width='100vw';cvs.style.height='auto'}}addEventListener('resize',resize);resize();
class Fighter{constructor(x,color,face,isCPU=false){this.x=x;this.y=540;this.vx=0;this.color=color;this.face=face;this.cpu=isCPU;this.hp=1000;this.ba=1000;this.state='idle';this.t=0;this.move=null;this.guard=false;this.rot=false;this.cool=0;this.hitDone=false;this.name='';this.eye=0;}
 start(id){let m=MOVES[id];if(!m||this.t>0)return;this.move=m;this.state=id;this.t=m.dur;this.hitDone=false;this.guard=id==='guard';this.rot=id==='rotate';this.name=m.name;if(m.move)this.x+=m.move*this.face;}
 update(dt,opp){this.eye+=dt; if(this.cool>0)this.cool-=dt; if(this.t>0){let old=this.t;this.t-=dt;if(this.move&&this.move.hit&&!this.hitDone){let e=this.move.dur-this.t,hit=this.move.hit;if(e>=hit.start&&e<=hit.end){let hb=this.hitbox(hit); if(rects(hb,opp.body())){this.hitDone=true;let dmg=this.move.dmg,bal=this.move.bal;if(opp.guard){dmg*=.22;bal*=1.45;opp.ba-=bal}else{opp.hp-=dmg;opp.ba-=bal;opp.x+=28*this.face}opp.name=(opp.guard?'ガード ':'被弾 ')+this.move.name;}}} if(this.t<=0){this.state='idle';this.move=null;this.guard=false;this.rot=false;}}
 if(this.ba<0)this.ba=0;if(this.hp<0)this.hp=0;if(this.ba<1000)this.ba+=18*dt;this.x=Math.max(80,Math.min(1200,this.x));}
 body(){return{x:this.x-28,y:this.y-165,w:56,h:165}}
 hitbox(h){return{x:this.x+h.x*this.face-(this.face<0?h.w:0),y:this.y+h.y,w:h.w,h:h.h}}
 draw(){ctx.save();ctx.translate(this.x,this.y);ctx.scale(this.face,1);let c=this.color;ctx.lineWidth=9;ctx.lineCap='round';ctx.strokeStyle='#111';ctx.fillStyle=c;
 let lean=0,leg=0,arm=0,knee=0,spin=false;if(this.state==='rotate'){spin=true;lean=10*Math.sin(this.t*25)}
 if(['dwit','hurigi','jump_spin'].includes(this.state))spin=true;if(this.state==='guard')arm=-25;
 // legs
 ctx.strokeStyle='#111';ctx.lineWidth=18;ctx.beginPath();ctx.moveTo(-15,-78);ctx.lineTo(-28,-5);ctx.moveTo(12,-78);ctx.lineTo(24,-5);ctx.stroke();ctx.strokeStyle=c;ctx.lineWidth=12;ctx.beginPath();ctx.moveTo(-15,-78);ctx.lineTo(-28,-5);ctx.moveTo(12,-78);ctx.lineTo(24,-5);ctx.stroke();
 // kick leg overlay
 if(['small','big','retreat_round','neryo'].includes(this.state)){ctx.strokeStyle='#111';ctx.lineWidth=18;ctx.beginPath();let high=this.state==='neryo'?-165:-88;ctx.moveTo(12,-85);ctx.lineTo(80,high);ctx.lineTo(this.state==='neryo'?92:145,high+8);ctx.stroke();ctx.strokeStyle=c;ctx.lineWidth=12;ctx.stroke();}
 if(this.state==='dwit'||this.state==='retreat_back'){ctx.strokeStyle='#111';ctx.lineWidth=18;ctx.beginPath();ctx.moveTo(-8,-82);ctx.lineTo(75,-80);ctx.lineTo(175,-80);ctx.stroke();ctx.strokeStyle=c;ctx.lineWidth=12;ctx.stroke();}
 if(this.state==='hurigi'||this.state==='jump_spin'){ctx.strokeStyle='#111';ctx.lineWidth=18;ctx.beginPath();ctx.moveTo(-8,-82);ctx.lineTo(72,-124);ctx.lineTo(178,-126);ctx.stroke();ctx.strokeStyle=c;ctx.lineWidth=12;ctx.stroke();}
 // body
 ctx.fillStyle=c;ctx.strokeStyle='#111';ctx.lineWidth=5;ctx.beginPath();ctx.roundRect(-38,-160,76,82,12);ctx.fill();ctx.stroke();ctx.fillStyle='#111';ctx.fillRect(-42,-78,84,12);
 // arms
 ctx.strokeStyle='#111';ctx.lineWidth=13;ctx.beginPath();ctx.moveTo(-32,-140);ctx.lineTo(-55,-108+arm);ctx.moveTo(32,-140);ctx.lineTo(55,-112+arm);ctx.stroke();ctx.strokeStyle=c;ctx.lineWidth=8;ctx.stroke();
 // head hair eyes
 ctx.fillStyle='#ffd9b0';ctx.strokeStyle='#111';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,-195,31,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#111';ctx.beginPath();ctx.arc(10,-198,3,0,7);ctx.arc(-10,-198,3,0,7);ctx.fill();ctx.fillStyle='#111';ctx.beginPath();ctx.arc(0,-222,28,Math.PI,0);ctx.fill();
 if(spin){ctx.fillStyle='#fff8';ctx.font='bold 20px sans-serif';ctx.fillText('↻',-12,-180)}
 ctx.restore();}
}
function rects(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
let p=new Fighter(300,'#1667d8',1),e=new Fighter(970,'#d93232',-1,true);let time=60,msg='';
function command(act){if(p.t>0&&p.state==='rotate'){if(act==='small')p.start('dwit'); if(act==='big')p.start('hurigi');return} if(p.t>0)return; if(act==='guard'){p.start('guard');return} if(act==='small'){if(dir.up)p.start('neryo');else if(dir.left)p.start('retreat_round');else p.start('small')} if(act==='big'){if(dir.up)p.start('jump_spin');else if(dir.left)p.start('retreat_back');else p.start('big')}}
function keydown(k){if(k==='ArrowLeft'||k==='ArrowRight'){let side=k==='ArrowLeft'?'left':'right',now=performance.now(); if(now-lastTap[side]<260){p.x+=(side==='right'?110:-110);p.name=side==='right'?'ステップイン':'バックステップ'} lastTap[side]=now;dir[side]=true} if(k==='ArrowUp')dir.up=true;if(k==='ArrowDown'){dir.down=true;if(p.t<=0)p.start('rotate')} if(k==='z')command('small');if(k==='x')command('big');if(k==='c')command('guard')}
function keyup(k){if(k==='ArrowLeft')dir.left=false;if(k==='ArrowRight')dir.right=false;if(k==='ArrowUp')dir.up=false;if(k==='ArrowDown')dir.down=false}
addEventListener('keydown',ev=>keydown(ev.key));addEventListener('keyup',ev=>keyup(ev.key));
document.querySelectorAll('button').forEach(b=>{let d=b.dataset.dir,a=b.dataset.act;b.addEventListener('pointerdown',ev=>{ev.preventDefault(); if(d){ if(d==='down'&&p.t<=0)p.start('rotate'); dir[d]=true; if((d==='left'||d==='right'))keydown(d==='left'?'ArrowLeft':'ArrowRight')} if(a)command(a)});b.addEventListener('pointerup',()=>{if(d)dir[d]=false});});
function cpu(dt){let dist=Math.abs(e.x-p.x);e.face=e.x>p.x?-1:1;if(e.t>0)return;if(dist>360)e.x-=70*dt;else if(dist<160)e.x+=90*dt;else if(Math.random()<.012){let r=Math.random();if(r<.2)e.start('guard');else if(r<.45)e.start('small');else if(r<.7)e.start('big');else if(r<.85)e.start('dwit');else e.start('hurigi')}}
function update(dt){time-=dt;if(p.t<=0){if(dir.left)p.x-=160*dt;if(dir.right)p.x+=160*dt}p.face=p.x<e.x?1:-1;e.face=e.x>p.x?-1:1;cpu(dt);p.update(dt,e);e.update(dt,p)}
function bar(x,y,w,h,val,color,label){ctx.fillStyle='#111';ctx.fillRect(x-3,y-3,w+6,h+6);ctx.fillStyle='#333';ctx.fillRect(x,y,w,h);ctx.fillStyle=color;ctx.fillRect(x,y,w*Math.max(0,val/1000),h);ctx.fillStyle='white';ctx.font='bold 22px sans-serif';ctx.fillText(label+' '+Math.ceil(val),x+12,y+h-8)}
function drawStage(){ctx.fillStyle='#79c9ff';ctx.fillRect(0,0,W,H);ctx.fillStyle='#7ab36b';for(let i=0;i<5;i++){ctx.beginPath();ctx.arc(120+i*280,330,150,Math.PI,0);ctx.fill()}ctx.fillStyle='#d9c08a';ctx.fillRect(0,350,W,40);ctx.fillStyle='#457';for(let i=0;i<15;i++)ctx.fillRect(i*100,325,10,65);ctx.fillRect(0,330,W,10);ctx.fillRect(0,360,W,10);ctx.fillStyle='#2863ad';ctx.fillRect(0,390,W,330);ctx.fillStyle='#d94646';ctx.fillRect(0,390,W,22);ctx.fillStyle='#0002';for(let i=0;i<20;i++)ctx.fillRect(i*70,390,1,330)}
function draw(){drawStage();bar(40,35,430,28,p.hp,'#20d340','PLAYER HP');bar(40,75,430,18,p.ba,'#2d8cff','BALANCE');bar(810,35,430,28,e.hp,'#20d340','CPU HP');bar(810,75,430,18,e.ba,'#d33','BALANCE');ctx.fillStyle='#111';ctx.fillRect(590,20,100,105);ctx.fillStyle='white';ctx.font='bold 56px sans-serif';ctx.fillText(Math.max(0,Math.ceil(time)),610,92);p.draw();e.draw();ctx.fillStyle='#000b';ctx.fillRect(28,130,360,150);ctx.fillStyle='white';ctx.font='bold 23px sans-serif';ctx.fillText('下：回転フェイント → 小:ティッチャギ / 大:ティフリギ',45,165);ctx.fillText('上＋小：ネリョチャギ　上＋大：跳び後ろ回し',45,202);ctx.fillText('後＋小/大：下がり蹴り　C/ガード：防御',45,239);ctx.font='bold 30px sans-serif';ctx.fillText(p.name||' ',270,330);ctx.fillText(e.name||' ',790,330);if(p.hp<=0||e.hp<=0||time<=0){ctx.fillStyle='#000a';ctx.fillRect(0,0,W,H);ctx.fillStyle='white';ctx.font='bold 72px sans-serif';ctx.fillText(p.hp>e.hp?'PLAYER WIN':p.hp<e.hp?'CPU WIN':'DRAW',430,350);}}
let last=performance.now();function loop(now){let dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
CanvasRenderingContext2D.prototype.roundRect??=function(x,y,w,h,r){this.beginPath();this.moveTo(x+r,y);this.arcTo(x+w,y,x+w,y+h,r);this.arcTo(x+w,y+h,x,y+h,r);this.arcTo(x,y+h,x,y,r);this.arcTo(x,y,x+w,y,r);return this};
