(()=>{
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const keys={left:false,right:false,up:false,down:false,small:false,big:false,guard:false};
const pressed={};let time=0,lastTap={left:-999,right:-999};
function setKey(k,v){keys[k]=v;document.querySelectorAll(`[data-key="${k}"]`).forEach(b=>b.classList.toggle('pressed',v));if(v){pressed[k]=true;if(k==='left'||k==='right'){if(time-lastTap[k]<18)pressed[k+'Double']=true;lastTap[k]=time;}}}
addEventListener('keydown',e=>{const m={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down',z:'small',Z:'small',x:'big',X:'big',c:'guard',C:'guard'};if(m[e.key]){e.preventDefault();setKey(m[e.key],true);}});
addEventListener('keyup',e=>{const m={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down',z:'small',Z:'small',x:'big',X:'big',c:'guard',C:'guard'};if(m[e.key])setKey(m[e.key],false);});
document.querySelectorAll('button[data-key]').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);setKey(k,true)});b.addEventListener('pointerup',e=>{e.preventDefault();setKey(k,false)});b.addEventListener('pointercancel',()=>setKey(k,false));});
const moves={small:{name:'小キック',dmg:45,bal:8,range:95,frames:[6,8,14],push:16},big:{name:'大キック',dmg:75,bal:15,range:125,frames:[10,10,20],push:26},naeryo:{name:'ネリョチャギ',dmg:70,bal:17,range:115,frames:[12,10,22],push:18},jumpSpin:{name:'跳び後ろ回し蹴り',dmg:105,bal:28,range:145,frames:[17,12,30],push:38},backSmall:{name:'下がりトルリョチャギ',dmg:55,bal:12,range:105,frames:[9,8,19],push:30,retreat:true},backBig:{name:'下がり跳びティッチャギ',dmg:90,bal:24,range:135,frames:[15,10,27],push:40,retreat:true},dwit:{name:'ティッチャギ（後ろ蹴り）',dmg:90,bal:18,range:135,frames:[8,8,22],push:44},dwi:{name:'ティフリギ（後ろ回し蹴り）',dmg:120,bal:32,range:155,frames:[13,10,34],push:55}};
class Fighter{constructor(x,color,name){this.x=x;this.y=415;this.color=color;this.name=name;this.f=1;this.hp=1000;this.balance=100;this.state='idle';this.t=0;this.move=null;this.hit=false;this.guard=false;this.aiCd=0;this.flash=0;this.msg='';}
start(s,t){this.state=s;this.t=t;this.hit=false;} attack(m){if(this.state==='attack')return;this.move=m;this.balance=Math.max(0,this.balance-m.bal);this.start('attack',m.frames[0]+m.frames[1]+m.frames[2]);this.msg=m.name;} active(){if(this.state!=='attack'||!this.move)return false;let total=this.move.frames[0]+this.move.frames[1]+this.move.frames[2],p=total-this.t;return p>=this.move.frames[0]&&p<this.move.frames[0]+this.move.frames[1];}
update(other,isPlayer){this.f=this.x<other.x?1:-1;this.guard=false;let vx=0;if(this.flash>0)this.flash--;if(this.state!=='idle'){this.t--;if(this.state==='step')vx=8*this.f;if(this.state==='back')vx=-8*this.f;if(this.state==='rotate'){}if(this.move?.retreat&&this.state==='attack')vx=-3*this.f;if(this.t<=0){this.state='idle';this.move=null;this.msg='';}}
 if(isPlayer)this.playerInput();else this.cpuInput(other); if(this.state==='idle'){if(isPlayer){if(keys.left)vx=-3.3;if(keys.right)vx=3.3;}this.balance=Math.min(100,this.balance+0.08)} this.x=Math.max(60,Math.min(900,this.x+vx));}
playerInput(){const fw=this.f===1?'right':'left',bk=this.f===1?'left':'right'; if(this.state==='idle'){if(pressed[fw+'Double'])this.start('step',13);else if(pressed[bk+'Double'])this.start('back',15);else if(keys.guard){this.guard=true;this.start('guard',3);}else if(pressed.down)this.start('rotate',28);else if(pressed.small)this.attack(keys.up?moves.naeryo:keys[bk]?moves.backSmall:moves.small);else if(pressed.big)this.attack(keys.up?moves.jumpSpin:keys[bk]?moves.backBig:moves.big);}else if(this.state==='rotate'){if(pressed.small)this.attack(moves.dwit);else if(pressed.big)this.attack(moves.dwi);}}
cpuInput(o){this.aiCd--;let d=Math.abs(this.x-o.x);if(this.state==='idle'&&this.aiCd<=0){this.aiCd=25+Math.random()*30;if(d>190)this.start('step',13);else if(d<75)this.start('back',15);else{let r=Math.random();if(r<.18){this.guard=true;this.start('guard',8)}else if(r<.32)this.start('rotate',24);else if(r<.62)this.attack(moves.small);else this.attack(moves.big);}}else if(this.state==='rotate'&&this.aiCd<18){if(Math.random()<.08)this.attack(Math.random()<.55?moves.dwit:moves.dwi);}}
draw(){ctx.save();ctx.translate(this.x,this.y);ctx.scale(this.f,1);if(this.flash)ctx.globalAlpha=.55;let c=this.color;ctx.lineWidth=7;ctx.lineCap='round';ctx.strokeStyle='#151515';ctx.fillStyle=c;let rot=this.state==='rotate'?Math.sin(time*.8)*.35:0;ctx.rotate(rot);ctx.fillRect(-26,-116,52,76);ctx.strokeRect(-26,-116,52,76);ctx.fillStyle='#111';ctx.fillRect(-34,-46,68,10);ctx.fillStyle='#f0c49d';ctx.beginPath();ctx.arc(0,-146,25,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#111';ctx.beginPath();ctx.arc(8,-149,3,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#151515';ctx.beginPath();ctx.moveTo(-24,-98);ctx.lineTo(-52,-76);ctx.lineTo(-38,-58);ctx.moveTo(24,-98);ctx.lineTo(52,-78);ctx.lineTo(40,-58);ctx.stroke();let k=0,high=0;if(this.state==='attack'){let total=this.move.frames[0]+this.move.frames[1]+this.move.frames[2];let p=(total-this.t)/total;k=Math.sin(Math.min(1,p*1.6)*Math.PI);high=(this.move===moves.naeryo||this.move===moves.jumpSpin||this.move===moves.dwi)?30:0;}ctx.beginPath();ctx.moveTo(-16,-40);ctx.lineTo(-34,0);ctx.lineTo(-42,28);ctx.moveTo(16,-40);ctx.lineTo(35+k*70,-5-k*(30+high));ctx.lineTo(55+k*(this.move?.range||60),20-k*(55+high));ctx.stroke();if(this.state==='guard'||this.guard){ctx.fillStyle='#333';ctx.fillRect(26,-116,18,68);ctx.strokeRect(26,-116,18,68)}ctx.restore();ctx.fillStyle='#fff';ctx.font='18px system-ui';ctx.textAlign='center';ctx.fillText(this.msg||this.state,this.x,this.y-190);}}
const p1=new Fighter(250,'#1266d6','PLAYER'),cpu=new Fighter(700,'#cc2b2b','CPU');
function hit(a,b){if(!a.active()||a.hit)return;let d=Math.abs(a.x-b.x);if(d<a.move.range){a.hit=true;let dmg=a.move.dmg;if(b.state==='guard'||b.guard){dmg=Math.floor(dmg*.2);b.balance=Math.max(0,b.balance-a.move.bal*1.4);b.msg='ガード';}else{b.balance=Math.max(0,b.balance-a.move.bal*2);b.flash=8;b.x+=a.f*a.move.push;if(b.balance<=0)dmg=Math.floor(dmg*1.35);}b.hp=Math.max(0,b.hp-dmg);}}
function stage(){let g=ctx.createLinearGradient(0,0,0,350);g.addColorStop(0,'#5bc4ff');g.addColorStop(1,'#e8f8ff');ctx.fillStyle=g;ctx.fillRect(0,0,960,540);ctx.fillStyle='#70ad68';ctx.beginPath();ctx.arc(190,360,230,Math.PI,0);ctx.fill();ctx.beginPath();ctx.arc(740,350,260,Math.PI,0);ctx.fill();ctx.fillStyle='#9b7658';ctx.fillRect(0,290,960,16);ctx.fillRect(0,325,960,14);for(let x=0;x<960;x+=90)ctx.fillRect(x,286,9,70);ctx.fillStyle='#245ca7';ctx.fillRect(0,340,960,200);ctx.fillStyle='#b72c2c';ctx.fillRect(0,340,960,17);ctx.fillStyle='#ffffff20';for(let x=0;x<960;x+=40)ctx.fillRect(x,340,1,200);}
function bar(x,y,w,h,v,max,col,label){ctx.fillStyle='#222';ctx.fillRect(x,y,w,h);ctx.fillStyle=col;ctx.fillRect(x,y,w*(v/max),h);ctx.strokeStyle='#111';ctx.strokeRect(x,y,w,h);ctx.fillStyle='#fff';ctx.font='16px system-ui';ctx.textAlign='center';ctx.fillText(label,x+w/2,y+h-6)}
function hud(){ctx.fillStyle='#111b';ctx.fillRect(0,0,960,78);ctx.fillStyle='#fff';ctx.font='22px system-ui';ctx.textAlign='left';ctx.fillText('PLAYER',28,26);ctx.textAlign='right';ctx.fillText('CPU',932,26);bar(28,36,360,24,p1.hp,1000,'#37d22f',p1.hp+'/1000');bar(572,36,360,24,cpu.hp,1000,'#37d22f',cpu.hp+'/1000');bar(140,64,250,10,p1.balance,100,'#1f80ff','');bar(570,64,250,10,cpu.balance,100,'#1f80ff','');ctx.fillStyle='#fff';ctx.font='18px system-ui';ctx.textAlign='center';ctx.fillText('←/→ 移動　前前:ステップイン　後後:バックステップ　↓:回転　Z/小　X/大　C/ガード',480,524);}
function win(){if(p1.hp<=0||cpu.hp<=0){ctx.fillStyle='#000b';ctx.fillRect(0,0,960,540);ctx.fillStyle='#fff';ctx.font='62px system-ui';ctx.textAlign='center';ctx.fillText(p1.hp<=0?'CPU WIN':'PLAYER WIN',480,260);ctx.font='24px system-ui';ctx.fillText('更新すると再戦できます',480,305);return true}return false;}
function loop(){time++;p1.update(cpu,true);cpu.update(p1,false);hit(p1,cpu);hit(cpu,p1);stage();hud();p1.draw();cpu.draw();win();for(const k in pressed)delete pressed[k];requestAnimationFrame(loop)}loop();
})();
